name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  data_processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Data Processing Script
        run: python financial_risk_dashboard/scripts/data_processing.py
      - name: Upload Processed Data as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed_data
          path: data/processed/combined_stock_metrics.csv

  model_training:
    needs: data_processing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download Processed Data Artifact
        uses: actions/download-artifact@v3 # Corrected: v3 instead of v2
        with:
          name: processed_data
          path: data/processed
      - name: Train Models & Generate Graphs
        run: |
          python financial_risk_dashboard/scripts/predictive_models.py
          python financial_risk_dashboard/visualizations/generate_graphs.py
      - name: Upload Graphs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: graphs
          path: graphs/

  deploy:
    needs: model_training
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Graphs Artifact  # Download the correct artifact
        uses: actions/download-artifact@v3 # Corrected: v3 instead of v2
        with:
          name: graphs  # Name of the artifact containing graphs
          path: graphs
      - name: Deploy to Server
        run: |
          echo "Deploying the project..."
          # ... (Your deployment logic)