name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Processing Script
        run: |
          python financial_risk_dashboard/scripts/data_processing.py

      - name: Run Unit Tests
        run: |
          if [ -d "tests" ]; then
            pytest tests/
          else
            echo "No tests directory found. Skipping tests."
          fi

      - name: Train Models & Generate Graphs
        run: |
          python financial_risk_dashboard/scripts/predictive_models.py
          python financial_risk_dashboard/visualizations/generate_graphs.py

      - name: Upload Graphs as Artifacts
        uses: actions/upload-artifact@v4  
        with:
          name: graphs
          path: graphs/

      - name: Upload Processed Data as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: processed_data
          path: data/processed/combined_stock_metrics.csv # Upload the created file

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.5

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Processed Data Artifacts
        uses: actions/download-artifact@v2
        with:
          name: processed_data
          path: data/processed  # Download to the correct location

      - name: Deploy to Server
        run: |
          echo "Deploying the project..."
          # ... (Your deployment logic)